<?php

$rules = [
    'align_multiline_comment' => true,
    'array_indentation'       => true,
    'array_push'              => true,
    'backtick_to_shell_exec'  => true,
    'binary_operator_spaces'  => [
        'default'   => 'single_space',
        'operators' => [
            '=>' => 'align',
        ],
    ],
    'clean_namespace'                 => true,
    'combine_consecutive_issets'      => true,
    'combine_consecutive_unsets'      => true,
    'combine_nested_dirname'          => true,
    'comment_to_phpdoc'               => true,
    'compact_nullable_typehint'       => true,
    'dir_constant'                    => true,
    'doctrine_annotation_braces'      => true,
    'doctrine_annotation_indentation' => true,
    'echo_tag_syntax'                 => [
        'format' => 'short',
    ],
    'ereg_to_preg'                                           => true,
    'explicit_indirect_variable'                             => true,
    'explicit_string_variable'                               => true,
    'full_opening_tag'                                       => true,
    'function_declaration'                                   => true,
    'function_to_constant'                                   => true,
    'function_typehint_space'                                => true,
    'heredoc_indentation'                                    => true,
    'list_syntax'                                            => true,
    'method_chaining_indentation'                            => true,
    'modernize_types_casting'                                => true,
    'multiline_comment_opening_closing'                      => true,
    'native_function_type_declaration_casing'                => true,
    'no_break_comment'                                       => true,
    'no_null_property_initialization'                        => true,
    'no_php4_constructor'                                    => true,
    'no_superfluous_phpdoc_tags'                             => true,
    'no_unneeded_curly_braces'                               => true,
    'no_unneeded_final_method'                               => true,
    'no_unset_cast'                                          => true,
    'no_unset_on_property'                                   => true,
    'no_useless_else'                                        => false,
    'no_useless_sprintf'                                     => true,
    'non_printable_character'                                => true,
    'nullable_type_declaration_for_default_null_value'       => true,
    'operator_linebreak'                                     => true,
    'ordered_class_elements'                                 => [
        'order'=> [
            'use_trait',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'construct',
            'destruct',
            'magic',
            'phpunit',
            'method',
        ],
    ],
    'ordered_interfaces'                                     => true,
    'ordered_traits'                                         => true,
    'php_unit_construct'                                     => true,
    'php_unit_expectation'                                   => true,
    'php_unit_fqcn_annotation'                               => true,
    'php_unit_method_casing'                                 => ['case' => 'snake_case'],
    'phpdoc_add_missing_param_annotation'                    => true,
    'phpdoc_align'                                           => true,
    'phpdoc_no_alias_tag'                                    => true,
    'phpdoc_order'                                           => true,
    'phpdoc_return_self_reference'                           => true,
    'phpdoc_scalar'                                          => true,
    'phpdoc_separation'                                      => true,
    'phpdoc_tag_type'                                        => true,
    'phpdoc_trim_consecutive_blank_line_separation'          => true,
    'phpdoc_types_order'                                     => true,
    'phpdoc_var_annotation_correct_order'                    => true,
    'return_assignment'                                      => true,
    'self_static_accessor'                                   => true,
    'simple_to_complex_string_variable'                      => true,
    // 'simplified_if_return'                                   => true,
    'simplified_null_return'                                 => true,
    'single_space_after_construct'                           => true,
    'standardize_increment'                                  => true,
    'ternary_to_null_coalescing'                             => true,
    'types_spaces'                                           => true,
    'array_syntax'                                           => ['syntax' => 'short'],
    'blank_line_after_namespace'                             => true,
    'blank_line_after_opening_tag'                           => true,
    'blank_line_before_statement'                            => ['statements' => ['return']],
    'braces'                                                 => true,
    'cast_spaces'                                            => true,
    'class_attributes_separation'                            => true,
    'class_definition'                                       => true,
    'concat_space'                                           => ['spacing' => 'one'],
    'declare_equal_normalize'                                => true,
    'elseif'                                                 => true,
    'encoding'                                               => true,
    'full_opening_tag'                                       => true,
    'fully_qualified_strict_types'                           => true, // added by Shift
    'function_declaration'                                   => true,
    'function_typehint_space'                                => true,
    'heredoc_to_nowdoc'                                      => true,
    'include'                                                => true,
    'increment_style'                                        => ['style' => 'post'],
    'indentation_type'                                       => true,
    'linebreak_after_opening_tag'                            => true,
    'line_ending'                                            => true,
    'lowercase_cast'                                         => true,
    'constant_case'                                          => true,
    'lowercase_keywords'                                     => true,
    'lowercase_static_reference'                             => true, // added from Symfony
    'magic_method_casing'                                    => true, // added from Symfony
    'magic_constant_casing'                                  => true,
    'method_argument_space'                                  => true,
    'native_function_casing'                                 => true,
    'no_alias_functions'                                     => true,
    'no_extra_blank_lines'                                   => ['tokens' => ['extra', 'throw', 'use', 'use_trait']],
    'no_blank_lines_after_class_opening'                     => true,
    'no_blank_lines_after_phpdoc'                            => true,
    'no_closing_tag'                                         => true,
    'no_empty_phpdoc'                                        => true,
    'no_empty_statement'                                     => true,
    'no_leading_import_slash'                                => true,
    'no_leading_namespace_whitespace'                        => true,
    'no_mixed_echo_print'                                    => ['use' => 'echo'],
    'no_multiline_whitespace_around_double_arrow'            => true,
    'multiline_whitespace_before_semicolons'                 => ['strategy' => 'no_multi_line'],
    'no_short_bool_cast'                                     => true,
    'no_singleline_whitespace_before_semicolons'             => true,
    'no_spaces_after_function_name'                          => true,
    'no_spaces_around_offset'                                => true,
    'no_spaces_inside_parenthesis'                           => true,
    'no_trailing_comma_in_list_call'                         => true,
    'no_trailing_comma_in_singleline_array'                  => true,
    'no_trailing_whitespace'                                 => true,
    'no_trailing_whitespace_in_comment'                      => true,
    'no_unused_imports'                                      => true,
    'no_unneeded_control_parentheses'                        => true,
    'no_unreachable_default_argument_value'                  => true,
    'no_useless_return'                                      => true,
    'no_whitespace_before_comma_in_array'                    => true,
    'no_whitespace_in_blank_line'                            => true,
    'normalize_index_brace'                                  => true,
    'not_operator_with_successor_space'                      => true,
    'object_operator_without_whitespace'                     => true,
    'ordered_imports'                                        => ['sort_algorithm' => 'alpha'],
    'phpdoc_indent'                                          => true,
    'phpdoc_inline_tag_normalizer'                           => true,
    'phpdoc_no_access'                                       => true,
    'phpdoc_no_package'                                      => true,
    'phpdoc_no_useless_inheritdoc'                           => true,
    'phpdoc_scalar'                                          => true,
    'phpdoc_single_line_var_spacing'                         => true,
    'phpdoc_summary'                                         => true,
    'phpdoc_to_comment'                                      => true,
    'phpdoc_trim'                                            => true,
    'phpdoc_types'                                           => true,
    'phpdoc_var_without_name'                                => true,
    'self_accessor'                                          => true,
    'short_scalar_cast'                                      => true,
    'simplified_null_return'                                 => true,
    'single_blank_line_at_eof'                               => true,
    'single_blank_line_before_namespace'                     => true,
    'single_class_element_per_statement'                     => true,
    'single_import_per_statement'                            => true,
    'single_line_after_imports'                              => true,
    'single_line_comment_style'                              => ['comment_types' => ['hash']],
    'single_quote'                                           => true,
    'space_after_semicolon'                                  => true,
    'standardize_not_equals'                                 => true,
    'switch_case_semicolon_to_colon'                         => true,
    'switch_case_space'                                      => true,
    'ternary_operator_spaces'                                => true,
    'trailing_comma_in_multiline'                            => true,
    'trim_array_spaces'                                      => true,
    'unary_operator_spaces'                                  => true,
    'use_arrow_functions'                                    => true,
    'visibility_required'                                    => ['elements' => ['method', 'property']],
    'whitespace_after_comma_in_array'                        => true,
    'return_type_declaration'                                => ['space_before' => 'none'],
    'psr_autoloading'                                        => true,
];

$finder = Symfony\Component\Finder\Finder::create()
    ->notPath('bootstrap/*')
    ->notPath('storage/*')
    ->notPath('resources/view/mail/*')
    ->notPath('vendor')
    ->in([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->name('*.php')
    ->notName('*.blade.php')
    ->notName('index.php')
    ->notName('server.php')
    ->notName('_ide_helper.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

$config = new PhpCsFixer\Config();

return $config
    ->setRiskyAllowed(true)
    ->setFinder($finder)
    ->setRules($rules)
    ->setUsingCache(false)
    ->setCacheFile(__DIR__ . '.php_cs.cache');
